### ISSUE TITLE
Hide and Seek lab

### ISSUE THREAD

**Issue by stephenfalck** [learn-co-curriculum/traversing-nested-objects#21]
When trying to run learn test i get the following error message: 

 1) "before all" hook:
     Uncaught SecurityError: localStorage is not available for opaque origins
      at Window.get localStorage [as localStorage] (node_modules/mocha-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at propagateToGlobal (node_modules/mocha-jsdom/index.js:108:27)
      at Object.done (node_modules/mocha-jsdom/index.js:59:9)
      at process.nextTick (node_modules/mocha-jsdom/node_modules/jsdom/lib/old-api.js:366:18)
      at _combinedTickCallback (internal/process/next_tick.js:132:7)
      at process._tickCallback (internal/process/next_tick.js:181:9)

and whenever i try o use nodejs index.js it says document is not defined

**Comment by drakeltheryuujin** [comment]
Hi @stephenfalck,

This lesson is not a lab. You may have opened this issue in the wrong place. This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
